# Build Skiko documentation
name: Doc

on:
  push:
    branches: [ master ]
  # Temporary, for testing. Remove!
  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  dokka:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - uses: actions/setup-java@v3
        name: 'Set up JDK 17'
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: 'Build Dokka documentation'
        run: bash -c 'JAVA_OPTS="-Xmx4g" ./gradlew --no-daemon -Pskiko.native.enabled=true -Pskiko.wasm.enabled=true -Pskiko.android.enabled=true :skiko:dokkaHtml'

      - name: 'Publish documentation'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./skiko/build/dokka/html
