name: WebTarget

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  web:
    runs-on: ubuntu-22.04
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        name: 'Set up JDK 21'
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'

      - name: 'Install dependencies'
        run: |
         sudo apt-get update
         sudo apt-get install libdbus-1-dev

      - name: 'Install emscripten'
        shell: bash
        run: |
          cd ./skiko
          sudo apt-get update -y
          sudo apt-get install binutils build-essential -y
          sudo apt-get install software-properties-common -y
          sudo apt-get install python-is-python3 git curl wget -y
          if [ -d ./emsdk ]; then
            cd ./emsdk
            git pull
          else
            git clone https://github.com/emscripten-core/emsdk.git
            cd ./emsdk
          fi
          ./emsdk install 3.1.50
          ./emsdk activate 3.1.50
          source ./emsdk_env.sh

      - name: 'Run WASM tests'
        shell: bash
        run: |
          cd ./skiko
          source ./emsdk/emsdk_env.sh
          ./gradlew --stacktrace --info -Pskiko.wasm.enabled=true -Pskiko.js.enabled=true -Pskiko.test.onci=true wasmJsTest
          ./gradlew --stacktrace --info -Pskiko.wasm.enabled=true -Pskiko.js.enabled=true publishSkikoWasmRuntimePublicationToMavenLocal

      - name: 'Run JS tests'
        shell: bash
        run: |
          cd ./skiko
          source ./emsdk/emsdk_env.sh
          ./gradlew --stacktrace --info -Pskiko.wasm.enabled=true -Pskiko.js.enabled=true -Pskiko.test.onci=true jsTest

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-wasm
          path: ./skiko/build/reports/tests
          retention-days: 5
